### ISSUE TITLE
GROVE connector GPIO12 -> 4 ?

### ISSUE THREAD

**Issue by sige1** [m5stack/M5-Schematic#1]
MODEL:M5CAMERA001
It was confirmed operation with MicroPython (psram).

Manual connect:
 GROVE connector --> BME280

import machine
i2c = machine.I2C(scl=machine.Pin(4), sda=machine.Pin(13))
i2c.scan()

118 <- get slave address 0x76(BME280)

thank you.

**Comment by graydonli** [comment]
Thanks sige1. I am going to update it. The new version of M5CAMERA, pinmap of BME280 is scl -> 23, sda -> 22.  Recently, we'll update a new code for M5CAMERA according to espressif camera reposity.

https://github.com/espressif/esp32-camera

**Comment by watson8544** [comment]
> MODEL:M5CAMERA001
> It was confirmed operation with MicroPython (psram).
> 
> Manual connect:
> GROVE connector --> BME280
> 
> import machine
> i2c = machine.I2C(scl=machine.Pin(4), sda=machine.Pin(13))
> i2c.scan()
> 
> 118 <- get slave address 0x76(BME280)
> 
> thank you.

Hello,
Here's the new firmware for M5Camera.

**Comment by graydonli** [comment]
> MODEL:M5CAMERA001
> It was confirmed operation with MicroPython (psram).
> 
> Manual connect:
> GROVE connector --> BME280
> 
> import machine
> i2c = machine.I2C(scl=machine.Pin(4), sda=machine.Pin(13))
> i2c.scan()
> 
> 118 <- get slave address 0x76(BME280)
> 
> thank you.

Hello,
Here's the new firmware for M5Camera.
https://github.com/m5stack/m5stack-cam-psram
