### ISSUE TITLE
LCD connection is advertised wrong everywhere on the internet.

### ISSUE THREAD

**Issue by ghost** [m5stack/M5-Schematic#12]
The LCD advertises a MISO connection on GPIO 19, which is wrong since the screen instead uses MOSI on GPIO23 (this is correct in the Basic Schematic).

Example of wrong pages:
https://docs.makerfactory.io/m5stack/core/fire/

**Comment by Gitshaoxiang** [comment]
Thanks your reply . i will talk to they change

**Comment by ghost** [comment]
Please Reopen while it's not done yet. otherwise you will forget about it.
