### ISSUE TITLE
Core Schematic Mistakes

### ISSUE THREAD

**Issue by zshivers** [m5stack/M5-Schematic#8]
There are a number of schematic issues:
1. Passive components around the IP5306 don't have reference designators. The output capacitors don't have values.
1. IP5306 KEY pin is has the net "PWR_KEY", which isn't referenced anywhere else in the schematic.
1. U10 does not have any pins for IIC
1. Section with U4 is labelled "Speaker", but it relates to EA3036 which is a power management chip.
1. Link for EA3036 datasheet is to an intranet address (192.13.102.98)

**Comment by zshivers** [comment]
@sio-funmatsu @watson8544

**Comment by ghost** [comment]
Also schematic for Fire Core is not available. No info about PSRAM pinout with a potentially problematic with BUS C connector (GPIO16,17 used for Groove UART, seems also used for PSRAM, so it's a conflict?)

Please publish the schematic for M5Stack Fire Core. Please again.

**Comment by Gitshaoxiang** [comment]
The GPIO 16 / 17 in Fire is connected to the PSRAM by default, so when you connect or stack other function modules, you need to avoid conflicts with these two pins to prevent the device from working properly and causing instability.

**Comment by ghost** [comment]
This is not an answer.
Please tell me

If I use FIRE CORE PSRAM, GROVE PORT C on m5go base  is unusable

Yes or no ?

**Comment by Gitshaoxiang** [comment]
YES, You can only use one of them（PSRAM or PORT C）
